# Generated by Django 2.0.2 on 2018-03-26 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_entry_name', models.TextField(max_length=256)),
                ('entry_date', models.DateTimeField()),
                ('remainder_date', models.DateTimeField()),
                ('check_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=264, unique='True')),
            ],
        ),
        migrations.AddField(
            model_name='listcontent',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hobby_app.Title'),
        ),
    ]
