# Generated by Django 2.0.2 on 2018-05-01 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hobby_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listcontent',
            old_name='label',
            new_name='lab_id',
        ),
        migrations.RemoveField(
            model_name='listcontent',
            name='entry_date',
        ),
        migrations.AddField(
            model_name='title',
            name='u_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
