# Generated by Django 2.0.2 on 2018-05-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobby_app', '0002_auto_20180501_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='title_name',
            field=models.CharField(max_length=264),
        ),
    ]
